import type { FairnessInput } from "./types";

/**
 * A single TextEncoder instance for the module.
 *
 * WebCrypto (`crypto.subtle`) works with bytes, not strings.
 * Therefore every string must be encoded to UTF-8 in a stable way before
 * hashing or HMAC signing.
 */
const textEncoder = new TextEncoder();

/**
 * Generates a cryptographically random seed and returns it as a hex string.
 *
 * Why hex:
 * - easy to store in JSON;
 * - easy to copy;
 * - easy to convert back to bytes for WebCrypto;
 * - no issues with binary characters.
 *
 * `crypto.getRandomValues` is the browser CSPRNG. It is suitable for
 * client-side random values. `serverSeed` must be generated by the trusted
 * server-side execution boundary and kept private until reveal.
 */
export function generateHexSeed(byteLength = 32): string {
  const bytes = new Uint8Array(byteLength);
  crypto.getRandomValues(bytes);
  return bytesToHex(bytes);
}

/**
 * Computes SHA-256 for a string and returns hex.
 *
 * In a provably fair system, SHA-256 is used as a commit:
 *
 * - the server publishes `serverSeedHash` ahead of time;
 * - after reveal, the server exposes `serverSeed`;
 * - anyone checks `SHA256(serverSeed) === serverSeedHash`.
 *
 * The same mechanism is used for frozen input: canonical input data is hashed
 * to produce `inputHash`.
 */
export async function sha256Hex(value: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    textEncoder.encode(value),
  );
  return bytesToHex(new Uint8Array(digest));
}

/**
 * Computes HMAC-SHA256.
 *
 * Why HMAC instead of simply SHA256(seed + message):
 * - HMAC is the standard way to derive pseudorandom blocks from a secret key;
 * - serverSeed is used as the key;
 * - message/context describes which random-stream block is being requested.
 *
 * The result is 32 bytes. These bytes are later consumed as deterministic
 * randomness for Fisher-Yates index selection.
 */
export async function hmacSha256(
  keyHex: string,
  message: string,
): Promise<Uint8Array> {
  /**
   * WebCrypto types key material as BufferSource.
   * Some TypeScript versions represent Uint8Array.buffer as ArrayBufferLike,
   * so we explicitly slice an ArrayBuffer for the exact view range.
   */
  const keyBytes = hexToBytes(keyHex);
  const keyBuffer = keyBytes.buffer.slice(
    keyBytes.byteOffset,
    keyBytes.byteOffset + keyBytes.byteLength,
  ) as ArrayBuffer;
  const key = await crypto.subtle.importKey(
    "raw",
    keyBuffer,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const signature = await crypto.subtle.sign(
    "HMAC",
    key,
    textEncoder.encode(message),
  );

  return new Uint8Array(signature);
}

/**
 * Hashes frozen input.
 *
 * This is one of the key functions in the system:
 *
 * - before freeze, participants can still join;
 * - after freeze, a FairnessInput object is created;
 * - `inputHash` is published;
 * - any later change to participants/prizes breaks the hash.
 *
 * Important: we do not hash an arbitrary object directly. We hash the output
 * of `canonicalizeInput`, so field names and ordering are predictable.
 */
export async function inputHash(input: FairnessInput): Promise<string> {
  return sha256Hex(canonicalizeInput(input));
}

/**
 * Canonical representation of a single join receipt before hashing.
 *
 * This data is used to build hash, which the player receives on join.
 * The current minimal set is:
 *
 * - round_id — so the same participant in different wheels has different hashes;
 * - id — public player ID/username;
 * - index — join order.
 *
 * More detailed participant entries can include joined_at, user_id, nonce, entry source,
 * and similar fields. The important rule is that the verifier must be able to
 * reconstruct the exact same fields.
 */
export function canonicalizeParticipant(
  roundId: string,
  participant: string,
  joinIndex: number,
): string {
  return JSON.stringify({
    round_id: roundId,
    id: participant,
    index: joinIndex,
  });
}

/**
 * Selects `winnerCount` unique participants using partial Fisher-Yates.
 *
 * Why partial:
 * - if there are 100000 participants and 3 prize places, shuffling everything
 *   is unnecessary;
 * - the first 3 Fisher-Yates steps are enough;
 * - the result is equivalent to taking the first N elements of a full
 *   Fisher-Yates shuffle.
 *
 * Algorithm:
 *
 * 1. Copy participants so the original frozen input is not mutated.
 * 2. For position `i`, choose random index `j` in range [i, end].
 * 3. Swap `pool[i]` and `pool[j]`.
 * 4. After N iterations, the first N elements are the winners.
 *
 * Winner uniqueness is guaranteed by the swap mechanism: the selected
 * participant is moved into the "done" prefix and cannot be selected again.
 */
export async function drawUnique(
  participants: string[],
  winnerCount: number,
  rng: HmacRandom,
): Promise<string[]> {
  const pool = [...participants];

  for (let i = 0; i < winnerCount; i++) {
    const j = i + (await rng.int(pool.length - i));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }

  return pool.slice(0, winnerCount);
}

/**
 * Deterministic random stream based on HMAC-SHA256.
 *
 * This is not "live random" during verification. It is a pseudorandom stream
 * fully determined by:
 *
 * - seedHex;
 * - context;
 * - nonce.
 *
 * Therefore, anyone with the same seed/context gets the same byte stream and
 * recalculates the same winners.
 *
 * Important for provably fair:
 * - before reveal, serverSeed is unknown;
 * - after reveal, serverSeed is public;
 * - the random stream becomes verifiable but no longer changeable.
 */
export class HmacRandom {
  /**
   * Buffer of the latest HMAC block.
   *
   * HMAC-SHA256 returns 32 bytes per call. To avoid calling WebCrypto for every
   * single byte, the block is stored in buffer and consumed gradually.
   */
  private buffer: Uint8Array = new Uint8Array();

  /**
   * HMAC block number.
   *
   * Every new block is computed as:
   * HMAC(seed, `${context}:${nonce}`)
   */
  private nonce = 0;

  /** Current read offset inside buffer. */
  private offset = 0;

  constructor(
    /** Hex seed used as the HMAC key. */
    private readonly seedHex: string,

    /**
     * Random stream context.
     *
     * In this system it includes algorithm, roundId, and clientSeed.
     * The context prevents accidental reuse of the same seed for unrelated
     * tasks that could otherwise share overlapping streams.
     */
    private readonly context: string,
  ) {}

  /**
   * Returns an integer in range [0, maxExclusive).
   *
   * Rejection sampling is used to remove modulo bias.
   *
   * Why not simply `randomBytes % maxExclusive`:
   * if the byte-space size is not divisible by maxExclusive, some values appear
   * slightly more often than others.
   *
   * Example:
   * - 1 byte gives 256 values;
   * - if the desired range is 0..9, 256 is not divisible by 10;
   * - values 0..5 would appear more often.
   *
   * To avoid that, the upper "tail" of the byte-space is rejected.
   */
  async int(maxExclusive: number): Promise<number> {
    if (!Number.isSafeInteger(maxExclusive) || maxExclusive <= 0) {
      throw new Error("Invalid random range");
    }

    const range = BigInt(maxExclusive);
    const maxInt64 = (BigInt(1) << BigInt(63)) - BigInt(1);
    const limit = maxInt64 - (maxInt64 % range);

    while (true) {
      const bytes = await this.bytes(8);
      let value = BigInt(0);

      for (const byte of bytes) {
        value = (value << BigInt(8)) + BigInt(byte);
      }

      value &= maxInt64;
      if (value < limit) {
        return Number(value % range);
      }
    }
  }

  /**
   * Reads `length` bytes from the deterministic stream.
   *
   * This is intentionally private: business logic does not need raw bytes,
   * it needs an unbiased integer for selecting indexes.
   */
  private async bytes(length: number): Promise<Uint8Array> {
    const output = new Uint8Array(length);

    for (let i = 0; i < length; i++) {
      output[i] = await this.byte();
    }

    return output;
  }

  /**
   * Returns one byte from the current HMAC block.
   *
   * If the block is exhausted, the next block is generated with a new nonce.
   */
  private async byte(): Promise<number> {
    if (this.offset >= this.buffer.length) {
      this.buffer = await hmacSha256(
        this.seedHex,
        `${this.context}:${this.nonce}`,
      );
      this.offset = 0;
      this.nonce++;
    }

    return this.buffer[this.offset++];
  }
}

/**
 * Canonicalizes frozen input before hashing.
 *
 * Why this matters:
 * JSON.stringify for ordinary objects is stable only when key creation order is
 * stable. Here we manually build an object with fixed snake_case keys and fixed
 * array ordering.
 *
 * What is included in the hash:
 * - participants — participant list, join hashes, and join order;
 * - prize_tiers — prize places.
 *
 * If any field changes after freeze, `inputHash` changes.
 */
function canonicalizeInput(input: FairnessInput): string {
  return JSON.stringify({
    participants: input.participants.map((participant) => ({
      id: participant.id,
      index: participant.index,
      hash: participant.hash,
    })),
    prize_tiers: input.prizeTiers.map((tier) => ({
      id: tier.id,
      name: tier.name,
      place: tier.place,
    })),
  });
}

/** Converts bytes to a hex string. */
function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Converts a hex string back to bytes.
 *
 * Used to import the HMAC key into WebCrypto.
 * Odd length or non-hex characters are considered invalid because such a seed
 * cannot be interpreted as bytes unambiguously.
 */
function hexToBytes(hex: string): Uint8Array {
  if (!/^[0-9a-f]+$/i.test(hex) || hex.length % 2 !== 0) {
    throw new Error("Invalid hex value");
  }

  const bytes = new Uint8Array(hex.length / 2);

  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }

  return bytes;
}
